const labels = {
  de: {
    navbarBrand: "Visualisierungen (BETA):",
    navbarBal: "Zeitverlauf",
    navbarKar: "Karte",
    navbarNet: "Netzwerk",
    navbarInf: "Info",
    loading: "Lade Daten...",
    infoText:
      "Herzlich Willkommen zu csVis! Um zu starten, klicken Sie einen der anderen Reiter an. Für weitere Informationen zur Bedienung, klicken sie in der Visualisierung auf den Info-Button gekennzeichnet durch ein 'i'.",
    balTitle: "Korrespondenzen von ",
    balTitleTo: "bis",
    balinfoButtonTitle: "Bedienung:",
    balInfoButtonWheel1: "Mausrad",
    balInfoButtonWheel2: ": Zoomen",
    balInfoButtonDrag1: "Drag",
    balInfoButtonDrag2: ": Position verschieben",
    balInfoButtonHover1: "Hovern",
    balInfoButtonHover2:
      " über Balkensegment: Zeigt Informationen über Briefwechsel an ",
    balInfoButtonClickSeg1: "Klick",
    balInfoButtonClickSeg2: " auf Balkensegment: Fixiert aktuelle Auswahl ",
    balInfoButtonClickCorresp1: "Klick",
    balInfoButtonClickCorresp2:
      " auf Korrespondenten im Seitenmenü: Zeigt nur Briefe der ausgewählten Person an",
    balInfoButtonClickLink1: '"Zu CorrespSearch"',
    balInfoButtonClickLink2:
      ": Ruft Suche mit ausgewählten Korrespondenten auf",
    balInfoButtonArrow1: "Pfeiltasten",
    balInfoButtonArrow2:
      ": Wechsel zwischen bereits ausgewählten Briefwechseln",
    balSideMenuLabel1: "Korrespondent 1: ",
    balSideMenuLabel2: "Weitere Korrespondenzen anzeigen",
    balSideMenuLabel3: "Korrespondent 2: ",
    balSideMenuStats1: "Briefe im Jahr ",
    balSideMenuStats2: "Anzahl Briefe: ",
    balSideMenuLink: "Zu CorrespSearch",
    balAxisLabelY: "Anzahl Briefe",
    balAxisLabelX: "Jahr",
    karHoverSliderButton: "Slider anzeigen",
    karHoverStatisticsButton: "Statistiken anzeigen",
    karHoverFilterButton: "Orte filtern",
    karSideMenuFilterPlaces1: "Briefe mit einem Ort",
    karSideMenuFilterPlaces2: "Briefe mit zwei Orten",
    karSideMenuFilterPlaces3: "Alle Briefe",
    karInfoButtonTitle: "Bedienung:",
    karInfoButtonWheel1: "Mausrad",
    karInfoButtonWheel2: ": Zoomen",
    karInfoButtonDrag1: "Drag",
    karInfoButtonDrag2: ": Position verschieben",
    karInfoButtonHover1: "Hovern",
    karInfoButtonHover2: ": Hebt Ort oder Verbindung hervor ",
    karInfoButtonClickPlace1: "Klick",
    karInfoButtonClickPlace2:
      " auf Ort oder Verbindung: Zeigt Briefdaten zum Ort oder der Verbindung an",
    karSliderLabel: "Jahrgänge",
    karInfoButtonSideMenuSlider2: "auf den ",
    karLabelUnknownPlace: "Unbekannter Ort",
    karLegendInfoLabel: `<p>Anzahl<br/>Briefe</p>`,
    karPopupTextLink1: "Alle Briefe aus ",
    karPopupTextLink2: " an diesem Ort",
    karPopupTextSender: "Absender: ",
    karPopupTextReceiver: "Empfänger: ",
    karPopupTextSenderPlace: "Sendeort: ",
    karPopupTextReceiverPlace: "Empfangsort: ",
    karPopupTextLetterLink: "Briefmetadaten in Trefferliste anzeigen",
    plaStaTitle: "Verteilung der Ortsangaben pro Jahr",
    plaStaNoPlaces: "0 Orte",
    plaSta1Place: "1 Ort",
    plaSta2Places: "2 Orte",
    plaStaAxisLabelY: "Anzahl Briefe",
    plaStaAxisLabelX: "Anzahl Orte",
    netInfoButtonTitle: "Bedienung:",
    netInfoButtonWheel1: "Mausrad",
    netInfoButtonWheel2: ": Zoomen",
    netInfoButtonDrag1: "Drag",
    netInfoButtonDrag2: ": Position verschieben",
    netInfoButtonHover1: "Hovern",
    netInfoButtonHover2: " über Verbindung oder Punkt: Zeigt Informationen an ",
    netInfoButtonHover3: " über Listeneintrag: Zeigt Informationen an ",
    netInfoButtonClick1: "Klick",
    netInfoButtonClick2:
      " auf Verbindung oder Punkt: Fixiert aktuelle Auswahl ",
    netInfoButtonClick3:
      " auf Briefsymbol in Liste: Zeigt Briefwechsel in Correspsearch an",
    netInfoButtonClick4:
      " auf Kreissymbol: Setzt aktuellen Listeneintrag als neuen Wurzelknoten",
    netLegendLabelTitle: "Geschlecht:",
    netLegendLabelMale: "männlich",
    netLegendLabelFemale: "weiblich",
    netLegendLabelUnknown: "unbekannt",
    netCorrespListTitle: "Korrespondenten:",
    netCorrespRootTitle: "Korrespondenzen von ",
    netCorrespRootTitleAlt: " Personen",
    netCorrespListText:
      "Auf Knoten oder Verbindung klicken, um Informationen über die Person(en) und ihre Korrespondenzen zu erhalten",
    netTooltipLabelDate: "N.N.",
    netTooltipPerson: "Person:",
    netTooltipSender: "Sender:",
    netTooltipReceiver: "Empfänger:",
    netTooltipLabelName: "Name:",
    netTooltipLabelBirth: "Geb.:",
    netTooltipLabelDeath: "Gest.:",
    netTooltipLabelGender: "Geschl.:",
    netTooltipLabelLetterCount: "Anzahl Briefe:",
    netHeadString1: "Briefwechsel zwischen ",
    netHeadString2: "und",
    netHeadString3: "Briefe:",
    netHeadString4: "Briefwechsel von",
  },
  en: {
    navbarBrand: "Visualizations:",
    navbarBal: "Bar Chart (BETA)",
    navbarKar: "Map Visualization (BETA)",
    navbarNet: "Network Visualization (BETA)",
    navbarInf: "Info",
    loading: "Loading data...",
    infoText:
      "Welcome to csVis! To get started, click one of the other tabs. For more information on how to use it, click the info button marked with an 'i' in the visualization.",
    balTitle: "Correspondences from ",
    balTitleTo: "to",
    balinfoButtonTitle: "Controls:",
    balInfoButtonWheel1: "Mouse wheel",
    balInfoButtonWheel2: ": Zoom",
    balInfoButtonDrag1: "Drag",
    balInfoButtonDrag2: ": Move position",
    balInfoButtonHover1: "Hover",
    balInfoButtonHover2:
      " over bar segment: Shows information about correspondence ",
    balInfoButtonClickSeg1: "Click",
    balInfoButtonClickSeg2: " on bar segment: Fixes current selection ",
    balInfoButtonClickCorresp1: "Click",
    balInfoButtonClickCorresp2:
      " on correspondent in side menu: Shows only letters of the selected person",
    balInfoButtonClickLink1: '"To CorrespSearch"',
    balInfoButtonClickLink2:
      ": Calls correspsearch with selected correspondent",
    balInfoButtonArrow1: "Arrow keys",
    balInfoButtonArrow2: ": Switch between already selected correspondences",
    balSideMenuLabel1: "Correspondent 1: ",
    balSideMenuLabel2: "Show more correspondences",
    balSideMenuLabel3: "Correspondent 2: ",
    balSideMenuStats1: "Letters in the year ",
    balSideMenuStats2: "Number of letters: ",
    balSideMenuLink: "To CorrespSearch",
    balAxisLabelY: "Number of letters",
    balAxisLabelX: "Year",
    karHoverSliderButton: "Show slider",
    karHoverStatisticsButton: "Show statistics",
    karHoverFilterButton: "Filter locations",
    karSideMenuFilterPlaces1: "Letters with one location",
    karSideMenuFilterPlaces2: "Letters with two locations",
    karSideMenuFilterPlaces3: "All letters",
    karInfoButtonTitle: "Controls:",
    karInfoButtonWheel1: "Mouse wheel",
    karInfoButtonWheel2: ": Zoom",
    karInfoButtonDrag1: "Drag",
    karInfoButtonDrag2: ": Move position",
    karInfoButtonHover1: "Hover",
    karInfoButtonHover2: ": Highlights location or connection ",
    karInfoButtonClickPlace1: "Click",
    karInfoButtonClickPlace2:
      " on location or connection: Shows letter data for the location or connection",
    karSliderLabel: "Years",
    karInfoButtonSideMenuSlider2: "on the ",
    karLabelUnknownPlace: "Unknown location",
    karLegendInfoLabel: `<p>Number of<br/>letters</p>`,
    karPopupTextLink1: "All letters from ",
    karPopupTextLink2: " at this location",
    karPopupTextSender: "Sender: ",
    karPopupTextReceiver: "Receiver: ",
    karPopupTextSenderPlace: "Sending location: ",
    karPopupTextReceiverPlace: "Receiving location: ",
    karPopupTextLetterLink: "Show letter metadata in correspsearch",
    plaStaTitle: "Distribution of locations per year",
    plaStaNoPlaces: "0 locations",
    plaSta1Place: "1 location",
    plaSta2Places: "2 locations",
    plaStaAxisLabelY: "Number of letters",
    plaStaAxisLabelX: "locations",
    netInfoButtonTitle: "Controls:",
    netInfoButtonWheel1: "Mouse wheel",
    netInfoButtonWheel2: ": Zoom",
    netInfoButtonDrag1: "Drag",
    netInfoButtonDrag2: ": Move position",
    netInfoButtonHover1: "Hover",
    netInfoButtonHover2: " over connection or point: Shows information ",
    netInfoButtonHover3: " over list entry: Shows information ",
    netInfoButtonClick1: "Click",
    netInfoButtonClick2: " on connection or point: Fixes current selection ",
    netInfoButtonClick3:
      " on letter symbol in list: Shows correspondence in CorrespSearch",
    netInfoButtonClick4:
      " on circle symbol: Sets current list entry as new root node",
    netLegendLabelTitle: "Gender:",
    netLegendLabelMale: "male",
    netLegendLabelFemale: "female",
    netLegendLabelUnknown: "unknown",
    netCorrespListTitle: "Correspondents:",
    netCorrespRootTitle: "Correspondences from ",
    netCorrespRootTitleAlt: " persons",
    netCorrespListText:
      "Click on node or connection to get information about the person(s) and their correspondences",
    netTooltipLabelDate: "N.N.",
    netTooltipPerson: "Person:",
    netTooltipSender: "Sender:",
    netTooltipReceiver: "Receiver:",
    netTooltipLabelName: "Name:",
    netTooltipLabelBirth: "Born:",
    netTooltipLabelDeath: "Died:",
    netTooltipLabelGender: "Gender:",
    netTooltipLabelLetterCount: "Number of letters:",
    netHeadString1: "Correspondence between ",
    netHeadString2: "and",
    netHeadString3: "Letters:",
    netHeadString4: "Correspondence from",
  },
};

export default labels;
